sudo: false
git:
  depth: 3

language: node_js
node_js:
  - "10"
  - "8"

branches:
  only:
    - master
    - develop
    - gh-pages

cache:
  npm: false
  yarn: false

env:
  - CI=true

script:
  - yarn test
  - yarn lint:ts

script_after:
  - yarn build

before_install:
  - curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn
