module.exports = {
	collectCoverageFrom: ["src/**/*.{js,jsx,ts,tsx}", "!src/**/*.d.ts"],
	setupFiles: ["react-app-polyfill/jsdom"],
	setupFilesAfterEnv: [],
	testMatch: ["<rootDir>/src/**/__tests__/**/*.{js,jsx,ts,tsx}", "<rootDir>/src/**/*.{spec,test}.{js,jsx,ts,tsx}"],
	testEnvironment: "jest-environment-jsdom-fourteen",
	transform: {
		"^.+\\.(js|jsx|ts|tsx)$": "<rootDir>/node_modules/babel-jest",
		"^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
		"^(?!.*\\.(js|jsx|ts|tsx|css|json)$)": "<rootDir>/config/jest/fileTransform.js",
	},
	transformIgnorePatterns: ["[/\\\\]node_modules[/\\\\].+\\.(js|jsx|ts|tsx)$", "^.+\\.module\\.(css|sass|scss)$"],
	modulePaths: [],
	moduleNameMapper: {
		"Root/(.*)": "<rootDir>/src/$1",
		"^asssets/(.*)": "<rootDir>/src/asssets/$1",
		"^components/(.*)": "<rootDir>/src/components/$1",
		"^hooks/(.*)": "<rootDir>/src/hooks/$1",
		"^helpers/(.*)": "<rootDir>/src/helpers/$1",
		"^screens/(.*)": "<rootDir>/src/screens/$1",
		"^scss/(.*)": "<rootDir>/src/scss/$1",
		"^react-native$": "react-native-web",
		"^.+\\.module\\.(css|sass|scss)$": "identity-obj-proxy",
	},
	moduleFileExtensions: ["web.js", "js", "web.ts", "ts", "web.tsx", "tsx", "json", "web.jsx", "jsx", "node"],
	watchPlugins: ["jest-watch-typeahead/filename", "jest-watch-typeahead/testname"],
};
